-- MySQL Script generated by MySQL Workbench
-- Wed May 24 00:54:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema torfresmaAPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema torfresmaAPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `torfresmaAPI` DEFAULT CHARACTER SET utf8 ;
USE `torfresmaAPI` ;

-- -----------------------------------------------------
-- Table `torfresmaAPI`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torfresmaAPI`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nm_user` VARCHAR(100) NOT NULL,
  `email_user` VARCHAR(100) NOT NULL,
  `senha_user` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_user_UNIQUE` (`email_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torfresmaAPI`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torfresmaAPI`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `titulo_post` VARCHAR(50) NOT NULL,
  `cont_post` LONGTEXT NOT NULL,
  `dt_post` DATE NOT NULL,
  `autor_post` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `torfresmaAPI`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
